### ISSUE TITLE
Revise state of the art

### ISSUE THREAD

**Issue by JJ** [JJ/2019-concurrent-ea-evostar#4]
Check other pool-based and concurrent implementations, including Erlang, Scala, and others like that. Maybe test Go (for speed)

**Comment by juanluck** [comment]
@JJ you may consider to include the text below in the state of the art. It makes reference to our EvAg model and how it manages concurrency. I didn't find the good spot to insert the text without breaking the style:

The EvAg model \cite{evag:gpem} is a locally concurrent and globally parallel evolutionary algorithm that leaves the management of the different agents (i.e. threads) to the underlying platform scheduler and displays an interesting feature: the model is able to scale seamlessly and take full advantage of CPU threads. In a first attempt to measure the scalability of the approach experiments were conducted  in \cite{wcci:evoag} for a single and a dual-core processor  showing that, for cost functions depassing some milliseconds of computing time, the model was able to achieve near linear speed-ups . This study was later on extended in \cite{DBLP:conf/evoW/LaredoBMG12} by scaling up the experimentation to up to 188 parallel machines\footnote{ Experiments were conducted in the NEC Nehalem cluster at the HPC center of the University of Stuttgart. See https://www.hlrs.de/de/systems/nec-cluster-laki-laki2/ for further details on the architecture. Accessed on November 2018).}. The reported speed-up was  $\times 960$ which is beyond the linear $\times 188$ that could be expected if local concurrency were not taken into account.
